# Generated by Django 6.0.3 on 2026-03-18 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barberos.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicios.servicio')),
            ],
        ),
    ]
