# Generated by Django 6.0.3 on 2026-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'EFECTIVO'), ('tarjeta', 'TARJETA'), ('transferencia', 'TRANSFERENCIA')], default='efectivo', max_length=15),
        ),
    ]
