# Generated by Django 6.0.3 on 2026-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('barbero', 'Barbero'), ('cliente', 'Cliente')], default='barbero', max_length=10),
        ),
    ]
